version: "3"

services:
  web_app:
    container_name: async-download-service
    env_file: .env
    build:
      context: app/
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    restart: always
    command: python server.py
    volumes:
      - ./app:/app
      - ./$PHOTOS_DIR_PATH/:/app/$PHOTOS_DIR_PATH/
